name: Trigger load daily reports 
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  build:
    name: Trigger load daily report
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: echo Hello, world!
