name: updates
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://axiearmy.club/api/academy/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
