name: updates
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        run: |
          curl --request GET \
          --url 'https://axiearmy.club/api/academy/cron' \
          --header 'authorization: Bearer $API_SECRET_KEY' \
          --header 'content-type: application/json'
